base_event = [
    "Bar_None",
    "Tempo Class_slow",
    "Tempo Class_fast",
    "Tempo Class_mid",
    "Note On_0",
    "Note On_1",
    "Note On_2",
    "Note On_3",
    "Note On_4",
    "Note On_5",
    "Note On_6",
    "Note On_7",
    "Note On_8",
    "Note On_9",
    "Note On_10",
    "Note On_11",
    "Note On_12",
    "Note On_13",
    "Note On_14",
    "Note On_15",
    "Note On_16",
    "Note On_17",
    "Note On_18",
    "Note On_19",
    "Note On_20",
    "Note On_21",
    "Note On_22",
    "Note On_23",
    "Note On_24",
    "Note On_25",
    "Note On_26",
    "Note On_27",
    "Note On_28",
    "Note On_29",
    "Note On_30",
    "Note On_31",
    "Note On_32",
    "Note On_33",
    "Note On_34",
    "Note On_35",
    "Note On_36",
    "Note On_37",
    "Note On_38",
    "Note On_39",
    "Note On_40",
    "Note On_41",
    "Note On_42",
    "Note On_43",
    "Note On_44",
    "Note On_45",
    "Note On_46",
    "Note On_47",
    "Note On_48",
    "Note On_49",
    "Note On_50",
    "Note On_51",
    "Note On_52",
    "Note On_53",
    "Note On_54",
    "Note On_55",
    "Note On_56",
    "Note On_57",
    "Note On_58",
    "Note On_59",
    "Note On_60",
    "Note On_61",
    "Note On_62",
    "Note On_63",
    "Note On_64",
    "Note On_65",
    "Note On_66",
    "Note On_67",
    "Note On_68",
    "Note On_69",
    "Note On_70",
    "Note On_71",
    "Note On_72",
    "Note On_73",
    "Note On_74",
    "Note On_75",
    "Note On_76",
    "Note On_77",
    "Note On_78",
    "Note On_79",
    "Note On_80",
    "Note On_81",
    "Note On_82",
    "Note On_83",
    "Note On_84",
    "Note On_85",
    "Note On_86",
    "Note On_87",
    "Note On_88",
    "Note On_89",
    "Note On_90",
    "Note On_91",
    "Note On_92",
    "Note On_93",
    "Note On_94",
    "Note On_95",
    "Note On_96",
    "Note On_97",
    "Note On_98",
    "Note On_99",
    "Note On_100",
    "Note On_101",
    "Note On_102",
    "Note On_103",
    "Note On_104",
    "Note On_105",
    "Note On_106",
    "Note On_107",
    "Note On_108",
    "Note On_109",
    "Note On_110",
    "Note On_111",
    "Note On_112",
    "Note On_113",
    "Note On_114",
    "Note On_115",
    "Note On_116",
    "Note On_117",
    "Note On_118",
    "Note On_119",
    "Note On_120",
    "Note On_121",
    "Note On_122",
    "Note On_123",
    "Note On_124",
    "Note On_125",
    "Note On_126",
    "Note On_127",
    "Tempo Value_0",
    "Tempo Value_1",
    "Tempo Value_2",
    "Tempo Value_3",
    "Tempo Value_4",
    "Tempo Value_5",
    "Tempo Value_6",
    "Tempo Value_7",
    "Tempo Value_8",
    "Tempo Value_9",
    "Tempo Value_10",
    "Tempo Value_11",
    "Tempo Value_12",
    "Tempo Value_13",
    "Tempo Value_14",
    "Tempo Value_15",
    "Tempo Value_16",
    "Tempo Value_17",
    "Tempo Value_18",
    "Tempo Value_19",
    "Tempo Value_20",
    "Tempo Value_21",
    "Tempo Value_22",
    "Tempo Value_23",
    "Tempo Value_24",
    "Tempo Value_25",
    "Tempo Value_26",
    "Tempo Value_27",
    "Tempo Value_28",
    "Tempo Value_29",
    "Tempo Value_30",
    "Tempo Value_31",
    "Tempo Value_32",
    "Tempo Value_33",
    "Tempo Value_34",
    "Tempo Value_35",
    "Tempo Value_36",
    "Tempo Value_37",
    "Tempo Value_38",
    "Tempo Value_39",
    "Tempo Value_40",
    "Tempo Value_41",
    "Tempo Value_42",
    "Tempo Value_43",
    "Tempo Value_44",
    "Tempo Value_45",
    "Tempo Value_46",
    "Tempo Value_47",
    "Tempo Value_48",
    "Tempo Value_49",
    "Tempo Value_50",
    "Tempo Value_51",
    "Tempo Value_52",
    "Tempo Value_53",
    "Tempo Value_54",
    "Tempo Value_55",
    "Tempo Value_56",
    "Tempo Value_57",
    "Tempo Value_58",
    "Tempo Value_59",
    "Note Velocity_0",
    "Note Velocity_1",
    "Note Velocity_2",
    "Note Velocity_3",
    "Note Velocity_4",
    "Note Velocity_5",
    "Note Velocity_6",
    "Note Velocity_7",
    "Note Velocity_8",
    "Note Velocity_9",
    "Note Velocity_10",
    "Note Velocity_11",
    "Note Velocity_12",
    "Note Velocity_13",
    "Note Velocity_14",
    "Note Velocity_15",
    "Note Velocity_16",
    "Note Velocity_17",
    "Note Velocity_18",
    "Note Velocity_19",
    "Note Velocity_20",
    "Note Velocity_21",
    "Note Velocity_22",
    "Note Velocity_23",
    "Note Velocity_24",
    "Note Velocity_25",
    "Note Velocity_26",
    "Note Velocity_27",
    "Note Velocity_28",
    "Note Velocity_29",
    "Note Velocity_30",
    "Note Velocity_31",
    "Chord_a",
    "Chord_aaug",
    "Chord_a#",
    "Chord_a#7",
    "Chord_a#dim",
    "Chord_a#aug",
    "Chord_a#m",
    "Chord_a7",
    "Chord_a7sus4",
    "Chord_adim",
    "Chord_adim7",
    "Chord_am",
    "Chord_am7",
    "Chord_am7b5",
    "Chord_amadd2",
    "Chord_amaj7",
    "Chord_asus4",
    "Chord_b",
    "Chord_baug",
    "Chord_bm",
    "Chord_b7",
    "Chord_bdim",
    "Chord_bm7",
    "Chord_bm7b5",
    "Chord_c",
    "Chord_cdim",
    "Chord_c#",
    "Chord_c#dim",
    "Chord_c#m",
    "Chord_c6",
    "Chord_c7",
    "Chord_c#7",
    "Chord_cadd2",
    "Chord_caug",
    "Chord_c#aug",
    "Chord_cm",
    "Chord_cm7",
    "Chord_cmaj7",
    "Chord_csus2",
    "Chord_csus4",
    "Chord_d",
    "Chord_daug",
    "Chord_d#aug",
    "Chord_ddim",
    "Chord_d#",
    "Chord_d#dim",
    "Chord_d#m",
    "Chord_d6",
    "Chord_d7",
    "Chord_d#7",
    "Chord_d7sus4",
    "Chord_dadd2",
    "Chord_dm",
    "Chord_dm6",
    "Chord_dm7",
    "Chord_dm7b5",
    "Chord_dsus2",
    "Chord_dsus4",
    "Chord_e",
    "Chord_edim",
    "Chord_e7",
    "Chord_e7sus4",
    "Chord_eaug",
    "Chord_em",
    "Chord_em7",
    "Chord_em7b5",
    "Chord_emaj7",
    "Chord_esus4",
    "Chord_f",
    "Chord_faug",
    "Chord_fdim",
    "Chord_f#",
    "Chord_f#aug",
    "Chord_f#7",
    "Chord_f#dim7",
    "Chord_f#dim",
    "Chord_f#m7",
    "Chord_f#m",
    "Chord_f#m7b5",
    "Chord_f6",
    "Chord_f7",
    "Chord_fadd2",
    "Chord_fdim7",
    "Chord_fm",
    "Chord_fm6",
    "Chord_fm7",
    "Chord_fmadd2",
    "Chord_fmaj7",
    "Chord_fsus2",
    "Chord_g",
    "Chord_gdim",
    "Chord_g#",
    "Chord_g#7",
    "Chord_g#dim",
    "Chord_g#aug",
    "Chord_g#m",
    "Chord_g6",
    "Chord_g7",
    "Chord_g7sus4",
    "Chord_gadd2",
    "Chord_gaug",
    "Chord_gdim7",
    "Chord_gm",
    "Chord_gm7",
    "Chord_gm7b5",
    "Chord_gsus2",
    "Chord_gsus4",
    "Chord_NN",
]


MIDI_EVENT_LABEL = {
    "time_signature": "Time Signature",
    "set_tempo": "Tempo",
    "key_signature": "Key Signature",
}
